---
sudo: required
services: docker

install:
  - bundle install

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - kitchen test
