---
language: ruby
services: docker
dist: xenial

env:
  global:
    - ROLE_NAME: <%= props.name %>
    - REPO_NAME: "ansible-${ROLE_NAME}"
  matrix:
    - ANSIBLE_VERSION: '2.5'
    - ANSIBLE_VERSION: '2.7'

before_install:
  # project directory must match role name
  - cd ../
  - mv $REPO_NAME $ROLE_NAME
  - cd $ROLE_NAME
  # tell bundler where to find Gemfile due to directory rename
  - export BUNDLE_GEMFILE="$(pwd)/Gemfile"

install:
  - sudo pip install ansible==$ANSIBLE_VERSION ansible-lint yamllint
  - bundle install

script:
  - yamllint .
  - ansible-lint .
  - ansible --version
  - kitchen list
  - bundle exec kitchen verify
